# {{- if .Values.backend.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: backend-ingress
#   namespace: {{ .Values.backend.namespace }}
#   annotations:
#     nginx.ingress.kubernetes.io/enable-cors: "true"
#     nginx.ingress.kubernetes.io/cors-allow-origin: "http://{{ .Values.frontend.ingress.host }}"
#     nginx.ingress.kubernetes.io/proxy-body-size: "50m"
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
# spec:
#   ingressClassName: {{ .Values.backend.ingress.className | default "nginx" }}
#   rules:
#     - host: {{ .Values.backend.ingress.host | default "backend.local" }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend
#                 port:
#                   number: {{ .Values.backend.service.port }}

#   {{- if .Values.backend.ingress.tls.enabled }}
#   tls:
#     - hosts:
#         - {{ .Values.backend.ingress.host }}
#       secretName: {{ .Values.backend.ingress.tls.secretName | default "backend-tls" }}
#   {{- end }}
# {{- end }}
