apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: database-namespace
spec:
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: tcp
  clusterIP: None   # Headless Service
  selector:
    app: {{ .Values.database.name }}

